# Generated by Django 4.1.3 on 2022-12-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_remove_readbooks_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='readbooks',
            name='read',
            field=models.BooleanField(default=0),
        ),
    ]
