# Generated by Django 4.1.3 on 2022-12-08 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_readbooks_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readbooks',
            name='user',
        ),
    ]
