# Generated by Django 4.1.3 on 2022-12-08 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0009_remove_books_read'),
        ('collection', '0004_remove_readbooks_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readbooks',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='library.books'),
        ),
    ]
