# Generated by Django 4.1.3 on 2022-12-09 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0005_alter_readbooks_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='user',
            new_name='users',
        ),
        migrations.AddField(
            model_name='readbooks',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
