# Generated by Django 4.1.3 on 2022-12-09 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0010_remove_books_user_books_user'),
        ('collection', '0006_rename_user_collection_users_readbooks_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readbooks',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.books'),
        ),
    ]
